# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/searce-cloud-products/gcf-artifacts/hello-docker:latest

service:
  type: LoadBalancer
  port: 80

userInput: "Welcome Searce!"
