apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
  labels: 
    app.kubernetes.io/name: "{{ .Release.Name }}"
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>{{.Values.userInput}}</h1>
    <p>This is a customized welcome page for Searce.</p>
    </body>
    </html>
